{% set name = "scikit-time" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ce190140e9cced27f50a0873bef13901af666568abfc65123efa676d6bb35a0c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py27 or osx or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - numpy
    - scipy
    - pip
    - pybind11
  run:
    - python
    - msmtools
    - {{ pin_compatible('numpy') }}
    - scipy
    - pint
    - scikit-learn

test:
  imports:
    - sktime

about:
  home: https://github.com/scikit-time/scikit-time
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Estimate and analyze Markov processes based on time series data.

  #doc_url: https://notyet.there.to/
  dev_url: https://github.com/scikit-time/scikit-time

extra:
  recipe-maintainers:
    - marscher
